name: backend ci cd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          pm2 start app.js
